
import gestion.des.employes.Employe;
import gestion.des.employes.Traitement;
import gestion.des.employes.societer;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MEHDI AROUBI
 */
public class liste extends javax.swing.JFrame {
 DefaultTableModel model = new DefaultTableModel();
    public liste() {
        initComponents();
       model.addColumn("codeEMP");
model.addColumn("Nom");
model.addColumn("prenom");
model.addColumn("adresse");
model.addColumn("telephone");
model.addColumn("sexe");
model.addColumn("Service");
table.setModel(model);
         remplircombox();
    }
     private void remplircombox(){
        try{
            comborech.removeAllItems();
            operations metier=new operations();
            ResultSet rs =metier.remplircombo();
            while(rs.next()){
                String CodeEmp=rs.getString("Numero");
                comborech.addItem(CodeEmp);
                
            }
        }catch(Exception ex){
            System.err.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Asd = new javax.swing.JCheckBox();
        des = new javax.swing.JCheckBox();
        btntri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comborech = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 520));
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 280, 470, 150);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setText("Trie par ordre alphabiteque:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 240, 27);

        Asd.setText("Ascendente");
        jPanel1.add(Asd);
        Asd.setBounds(40, 50, 150, 23);

        des.setText("Descendente");
        jPanel1.add(des);
        des.setBounds(40, 80, 150, 23);

        btntri.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btntri.setText("Trie");
        btntri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntriActionPerformed(evt);
            }
        });
        jPanel1.add(btntri);
        btntri.setBounds(80, 120, 80, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 60, 300, 160);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rechercher par Numero");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 240, 180, 30);

        comborech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comborech);
        comborech.setBounds(220, 240, 100, 30);

        jButton1.setText("chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 240, 90, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setText("Liste Des Employés");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 10, 260, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/projetJava.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 490, 430);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8-logout-rounded-up-30.png"))); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 440, 130, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8-undo-30.png"))); // NOI18N
        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(23, 443, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntriActionPerformed
       
        operations metier1 = new operations();
        model.setRowCount(0);
         String code=comborech.getSelectedItem().toString();
        try {
            if (des.isSelected()){
            ArrayList<Employe> liste = metier1.trieDes(code);
           Object[] row=new Object[7];
           for(int i =0;i<liste.size();i++){
               row[0]=liste.get(i).getCodeEmp();
                 row[1]=liste.get(i).getNom();
                   row[2]=liste.get(i).getPrenom();
                   row[3]=liste.get(i).getAdresse();
                   row[4]=liste.get(i).getTelephone();
                   row[5]=liste.get(i).getSex();
                   row[6]=liste.get(i).getService();
                     model.addRow(row);     
       }
               table.setModel(model);}
            else if (Asd.isSelected()){
                   operations metier = new operations();
                ArrayList<Employe> list = metier.trieAsd(code);
           Object[] row=new Object[7];
           for(int i =0;i<list.size();i++){
               row[0]=list.get(i).getCodeEmp();
                 row[1]=list.get(i).getNom();
                   row[2]=list.get(i).getPrenom();
                   row[3]=list.get(i).getAdresse();
                   row[4]=list.get(i).getTelephone();
                   row[5]=list.get(i).getSex();
                   row[6]=list.get(i).getService();
                     model.addRow(row);     
       }
               table.setModel(model);}
       }catch (Exception e) { System.err.println(e);
       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_btntriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    operations metier = new operations();
          
        try {
            model.setRowCount(0);
            ArrayList<Employe> list = metier.chercherListEmp(comborech.getSelectedItem().toString());
           Object[] row=new Object[7];
           for(int i =0;i<list.size();i++){
               row[0]=list.get(i).getCodeEmp();
                 row[1]=list.get(i).getNom();
                   row[2]=list.get(i).getPrenom();
                   row[3]=list.get(i).getAdresse();
                   row[4]=list.get(i).getTelephone();
                   row[5]=list.get(i).getSex();
                   row[6]=list.get(i).getService();
                     model.addRow(row);     
       }
               table.setModel(model);
           if (model.getRowCount () == 0){JOptionPane.showMessageDialog(null,"il y a aucun employe correspond a  ce numero");
       
       }
       }catch (Exception e) { System.err.println(e);
       JOptionPane.showMessageDialog(null,e.getMessage());
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               societe s = new societe();
               s.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new liste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Asd;
    private javax.swing.JButton btntri;
    private javax.swing.JComboBox<String> comborech;
    private javax.swing.JCheckBox des;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
